#!/bin/bash

clear; cat tmp_list | perl -ne 'if (/PCI: Bus 2/ ... /MEM window: /){print}' | awk '{print NR"\t"$0}' | awk '{if($1 < 6){printf ("%s\n",$0) > "/tmp/f1"}else{if($1>5 && $1<11){printf ("%s\n",$0) > "/tmp/f2"}}}'; sdiff -w 160 /tmp/f1 /tmp/f2 ; rm /tmp/f1 /tmp/f2
