package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Hello.idl
* Wednesday, March 10, 2004 2:52:33 PM EST
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
  String howOldAreYou ();
} // interface HelloOperations
