#!/bin/bash

set -x

# Root directory of all code units
SEARCH_DIR=$1

# Place to host generated HTML files
HOST_DIR="${HOME}/codehopper"
rm -rf ${HOST_DIR}
mkdir -p ${HOST_DIR}

###################
#
# Build TOC page
#
###################

TOC=${HOST_DIR}/toc.html
rm -f ${TOC}
touch ${TOC}

# add header tags to TOC
echo "<html><head><title>Top Directories</title></head><body>" >> ${TOC}

FILES=$(find ${search_dir} -type d)

for f in "${FILES[@]}"
do
	
	if [ -f "${f}" ]
	then

		

	fi

done

# add footer tags to TOC
echo "</body></html>" >> ${TOC}

